config/routes.rb
Rails.application.routes.draw do
 
  resources :doctors
  resources :patients
 resources :appointments
 
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
    validates :name,  presence: true
    has_many :appointments
    has_many :patients, through: :appointments

    def self.search(search)
      where("name LIKE ?", "%#{search}%") 
    end
    
end

app/models/patient.rb
class Patient < ActiveRecord::Base
   
    has_many :appointments
    has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
   
    def index
        @appointments = Patient.all
        @doctors_assigned =  Patient.find_by(name: "Alexandro Navarro").doctors
        @doctor = Doctor.find_by(name: @name_of_doctor)
    end
    
    def show
        find_appointment
    end
    
    def new
        @appointment = Appointment.new
        @patient = Patient.new
    end
    
    def create
        @appointment = Appointment.new(appointment_params)
        if @appointment.save
            redirect_to @appointment
        else
            render "New"
        end
    end
    
    
    private
    
    def appointment_params
        params.require(:appointment).permit(:date, :doctor_id, :patient_id)
    end
    
    def find_appointment
        @appointment = Appointment.find(params[:id])
    end
    
    def go_doctors
        @doctor_signup = Doctor.find(params[:id])
    end
    
    
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @list_patients = []
    if params[:search]
      @doctors_exists = Doctor.where(name: params[:search])
      if @doctors_exists.exists?
         @list_patients = Doctor.find_by(name: params[:search]).patients.order('created_at DESC')
      end  
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @list_doctors = []
    if params[:search]
      @patient_exists = Patient.where(name: params[:search])
      if @patient_exists.exists?
         @list_doctors = Patient.find_by(name: params[:search]).doctors.order("created_at DESC")
      end
    end  
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:id, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<div class = "container">
 <div class = "row">
   <%= form_for(@appointment) do |f| %>
     <br>
      <%= f.label :date, "Schedule an appointment" %><br>
      <br>
      <hr>
      <%= f.label :doctor, "Please select the name of the doctor" %><br>
      <%= f.collection_select(:doctor_id, Doctor.all, :id, :name, prompt: true) %><br>
      <br>
      <%= f.label :Patient, "Please select your username" %><br>
      <%= f.collection_select(:patient_id, Patient.all, :id, :name, prompt: true) %><br>
      <br>
      <br>
      <hr>
      <strong><%= f.submit %></strong>
   <% end %>
 </div> 
</div>

app/views/appointments/index.html.erb
<section id = "make-appointment"> 
 <div class = "container">
  <div class = "row">
   <div class = "col-md-6 pagination-centered center-block align-content">
       <!-- <ul class = "list-inline">
            <li id = "log-in"><h5><a>Log In</a></h5></li>
            <li id = "sign-up"><h5><a>Sign Up</a></h5></li>
        </ul> 
     <hr> -->
          <div class="list-group list-option">
        
          <div class="list-group-item list-group-item-action option-object"><h5><%= link_to "Doctors Board", doctors_path, class: "list-group-item-heading" %></h5>
          <p class="list-group-item-text">Portal for Doctors management (Medical Utilities)</p></div>
       
       
          <div class="list-group-item list-group-item-action option-object"><h5><%= link_to "Patients", patients_path, class: "list-group-item-heading" %></h5>
          <p class="list-group-item-text">Appoinment Information - Medical Inquiries - Pharmacy</p></div>

          </div>
      
    </div>
   </div>
   </div>
  </div>
 </div>
</section>

<!--   <h5 class="list-group-item-heading">#<= link_to "Sign up for Doctors", new_doctor_path, class:"list-group-item list-group-item-action active"  %></h5>
      <h5 class="list-group-item-heading">#<= link_to "Sign up for Patients", new_patient_path, class:"list-group-item list-group-item-action active"  %></h5>
  -->

app/views/appointments/new.html.erb
<%= render "form" %>

app/views/appointments/show.html.erb
<%= @appointment.doctor.name %></br>
<%= @appointment.patient.name %></br>
<%= @appointment.date_appointment %>

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name %><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<div class = "container">
 <div class = "row"></div>  
  <%= form_tag(doctors_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "please enter your name" %>
      <%= submit_tag "Search", :name => nil %>
      <br>
      <br>
      <div>
       <% if @list_patients.present? %>
          <%= @list_patients.each do |patient| %>
          <p>Appointment for patient <strong><%= patient.name %></strong></p>
          <hr>
          <br>
          <% end %>
       <% else %>
           <h5>Your name is not on our database, please <strong><%= link_to "registry", new_doctor_path %></strong>.</h5>
       <% end %>
  <% end %>         
     </div>
 </div>  
</div>  






<!-- <p id="notice"><= notice %></p>

<h1></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>lete, data: { confirm: 'Are you sure?' } %> -->

app/views/doctors/new.html.erb
<div class= "container">
 <div class = "row">    
    <h5>Please enter your name and  submit</h5>
    <%= render 'form' %>
    <br>
    <br>
    <%= link_to 'Back', doctors_path %>
 </div>
</div>

app/views/doctors/show.html.erb
<div class = "container">
 <div class = "row">
   <p id="notice"><%= notice %></p>

   <%= link_to 'Edit', edit_doctor_path(@doctor) %> |
   <%= link_to 'Back', doctors_path %>
  
 </div>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
     
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render "shared/header" %>
 <%= yield %>
 <%= render "shared/footer" %>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient's name from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name %><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>
<div class = "container">
 <div class = "row"></div>  
  <%= form_tag(patients_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "please enter your name" %>
      <%= submit_tag "Search", :name => nil %>
      <br>
      <br>
      <div>
       <% if @list_doctors.present? %>
          <br>
          <h5>To schedule a new appointment click <strong><%= link_to "Here", new_appointment_path %></strong>.</h5>
          <hr>
          <%= @list_doctors.each do |patient| %>
          <p>Appointment with Doctor <strong><%= patient.name %></strong></p>
          <hr>
          <br>
          <% end %>
       <% else %>
           <h5>your name is not on our database, please <strong><%= link_to "registry", new_patient_path %></strong>.</h5>
       <% end %>
  <% end %>         
     </div>
 </div>  
</div>



<!-- <h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <#% #@patients.each do |patient| %>
      <tr>
        <td><#%= #link_to 'Show', patient %></td>
        <td><#%= #link_to 'Edit', edit_patient_path(patient) %></td>
        <td><#%= #link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <#% end %>
  </tbody>
</table>

<br>

<#%= link_to 'New Patient', new_patient_path %> -->

app/views/patients/new.html.erb
<div class= "container">
 <div class = "row">    
    <h5>Please enter your name and  submit</h5>
    <%= render 'form' %>
    <br>
    <br>
    <%= link_to 'Back', patients_path %>
 </div>
</div>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<%= @patient.name %>
<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/shared/_footer.html.erb
<div class="footer navbar-fixed-bottom panel-footer">
 <div class = "container">
  <div class = "row">
   <h5> Doctor's Appointment App Footer by Alexandro Pequeno</h5>      
  </div>     
 </div>    
</div> 

app/views/shared/_header.html.erb
  <div class="container-fluid">    
    <nav class="navbar navbar-default">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Home <span class="sr-only">(current)</span></a></li> <!-- class="active" -->
            <li><a href="#">About</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
   </div><!-- /.container -->
   